In [8]:
import numpy as np
from sklearn.datasets import load_diabetes


In [13]:
# Load the diabetes dataset
diabetes_data = load_diabetes()

# Get the features (X) and target (y)
X = diabetes_data.data  # Features (independent variables)
y = diabetes_data.target  # Target (dependent variable)

In [14]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [16]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [18]:
from sklearn.model_selection import train_test_split


In [20]:
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression

In [22]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 3)

In [24]:
X_train.shape

(353, 10)

In [26]:
lr = LinearRegression()

In [29]:
lr.fit(X_train,y_train)

LinearRegression()

In [33]:
y_pred = lr.predict(X_test)

In [35]:
lr.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [37]:
lr.intercept_

np.float64(153.13441535285003)

In [58]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

0.4161792211496942


Now we make the Linear Regression class from scratch

In [80]:
class MultipleRegression:
    def __init__(self):
        self.coef = None
        self.intercept = None

    def fit(self, X_train,y_train):
        # print(X_train.shape) checking if it takes the training data or not
        # now we add a column containg only 1s in the dataset of x train
        X_train = np.column_stack((np.ones(X_train.shape[0]), X_train))
        # print(X_train)

        coeff_matrix = np.linalg.inv((X_train.T).dot(X_train)).dot(X_train.T).dot(y_train)
        # the first index is the intercept and the rest are the coefficients
        self.intercept = coeff_matrix[0]
        self.coef = coeff_matrix[1:]

        print(self.intercept)
        print(self.coef)


    def predict(self, X_test):
        y_pred = np.dot(X_test,self.coef) + self.intercept

        print(r2_score(y_test,y_pred))
        return y_pred

In [81]:
reg = MultipleRegression()

In [82]:
reg.fit(X_train,y_train)

153.13441535285006
[  -1.13744712 -212.8867836   540.45536994  345.20621542 -938.23814645
  516.62060367  172.85885498  267.87535242  732.63230159   70.07849485]


In [83]:
reg.predict(X_test)

0.41617922114969497


array([ 99.48235947, 181.25429903, 106.61572846, 123.10541923,
       183.04909567,  83.29913847, 130.54854188, 233.85654301,
       155.00942627, 171.46626454, 171.06003791, 192.94190885,
       147.25129841, 214.5307459 ,  47.50252863, 142.43786422,
       119.95723033, 209.7179434 , 185.71531692, 147.23625586,
       150.40785093, 102.60018559, 170.78899034, 177.8219416 ,
       152.40388316, 187.08466299, 197.72314739, 204.83066546,
       132.09655487, 158.42112429, 260.54948673, 125.48180691,
       195.29165994, 125.76882485, 163.21646899,  58.37895843,
       158.14323269, 103.4034084 , 128.04980829, 161.3128156 ,
       146.00080757, 219.57659671, 126.64096152, 131.12134464,
       150.1627216 ,  92.3404223 , 120.10323463, 261.33608538,
       150.22171365, 197.82772808, 145.97361477, 104.56119742,
       139.47230609, 192.90101701, 159.2347891 , 135.21956019,
       120.30423162, 262.94731714, 255.46123067, 151.24338655,
       153.11282489, 128.59191597,  69.02540213, 136.99